MultiLanguageNpcData['tw'][64977] = {name = "瑪瑙雲蛟", subname = nil}
MultiLanguageNpcData['tw'][65149] = {name = "卡拉西瓦·羅爾", subname = nil}
MultiLanguageNpcData['tw'][65191] = {name = "貓鼬", subname = nil}
MultiLanguageNpcData['tw'][65192] = {name = "小貓鼬", subname = nil}
MultiLanguageNpcData['tw'][65204] = {name = "豔光螢火蟲", subname = nil}
MultiLanguageNpcData['tw'][65205] = {name = "鑠金飛蛾", subname = nil}
MultiLanguageNpcData['tw'][65206] = {name = "黃金麝香貓", subname = nil}
MultiLanguageNpcData['tw'][65207] = {name = "小黃金麝香貓", subname = nil}
MultiLanguageNpcData['tw'][65209] = {name = "水舞浮黽", subname = nil}
MultiLanguageNpcData['tw'][65211] = {name = "黃腹牛蛙", subname = nil}
MultiLanguageNpcData['tw'][65223] = {name = "亡首蟑螂", subname = nil}
MultiLanguageNpcData['tw'][65247] = {name = "Player Clone (TEMP)", subname = nil}
MultiLanguageNpcData['tw'][65343] = {name = "骸骨蜘蛛", subname = nil}
MultiLanguageNpcData['tw'][65395] = {name = "卡拉西瓦·伊克", subname = nil}
MultiLanguageNpcData['tw'][65396] = {name = "卡拉西瓦·寇爾", subname = nil}
MultiLanguageNpcData['tw'][65397] = {name = "卡拉西瓦·科里克", subname = nil}
MultiLanguageNpcData['tw'][65398] = {name = "卡拉西瓦·絲拉", subname = nil}
MultiLanguageNpcData['tw'][65434] = {name = "General Purpose Bunny ZTO", subname = nil}
MultiLanguageNpcData['tw'][65443] = {name = "炸彈目標", subname = nil}
MultiLanguageNpcData['tw'][65445] = {name = "螳螂人", subname = nil}
MultiLanguageNpcData['tw'][65446] = {name = "哥布林船長", subname = nil}
MultiLanguageNpcData['tw'][65447] = {name = "哥布林海軍", subname = nil}
MultiLanguageNpcData['tw'][65449] = {name = "哥布林船員", subname = nil}
MultiLanguageNpcData['tw'][65561] = {name = "博學行者阿洲", subname = nil}
MultiLanguageNpcData['tw'][65596] = {name = "里歐坎尼機器人", subname = nil}
MultiLanguageNpcData['tw'][65630] = {name = "雷王", subname = nil}
MultiLanguageNpcData['tw'][65648] = {name = "王老先生", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][65651] = {name = "林塞", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][65655] = {name = "艾里克·戴維森", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][65656] = {name = "比爾·圓盾", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][65725] = {name = "雲光", subname = nil}
MultiLanguageNpcData['tw'][65758] = {name = "XE-321炸彈機器人", subname = nil}
MultiLanguageNpcData['tw'][65763] = {name = "歐索射樹車", subname = nil}
MultiLanguageNpcData['tw'][65764] = {name = "歐索入侵者", subname = nil}
MultiLanguageNpcData['tw'][65766] = {name = "老秦", subname = nil}
MultiLanguageNpcData['tw'][65767] = {name = "卡拉西瓦·伊克", subname = nil}
MultiLanguageNpcData['tw'][65771] = {name = "林·默襲", subname = nil}
MultiLanguageNpcData['tw'][65780] = {name = "恭大", subname = nil}
MultiLanguageNpcData['tw'][65781] = {name = "蘇納·默襲", subname = nil}
MultiLanguageNpcData['tw'][65782] = {name = "班·熊心", subname = nil}
MultiLanguageNpcData['tw'][65843] = {name = "強臂旋翼機", subname = nil}
MultiLanguageNpcData['tw'][65895] = {name = "怒兆", subname = "玄牛"}
MultiLanguageNpcData['tw'][65898] = {name = "赤吉", subname = "紅鶴"}
MultiLanguageNpcData['tw'][65902] = {name = "雪怒", subname = nil}
MultiLanguageNpcData['tw'][65904] = {name = "玉龍", subname = "玉蛟"}
MultiLanguageNpcData['tw'][65961] = {name = "山谷之門", subname = nil}
MultiLanguageNpcData['tw'][66036] = {name = "螳螂人飛行者", subname = nil}
MultiLanguageNpcData['tw'][66053] = {name = "利文·曦刃", subname = nil}
MultiLanguageNpcData['tw'][66055] = {name = "昆·秋光", subname = nil}
MultiLanguageNpcData['tw'][66056] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][66057] = {name = "茹克·石趾", subname = nil}
MultiLanguageNpcData['tw'][66058] = {name = "『和諧雅士』值", subname = "護法"}
MultiLanguageNpcData['tw'][66059] = {name = "何·軟足", subname = nil}
MultiLanguageNpcData['tw'][66061] = {name = "安吉·秋光", subname = nil}
MultiLanguageNpcData['tw'][66064] = {name = "酒保湯羅", subname = "旅店老闆"}
MultiLanguageNpcData['tw'][66065] = {name = "廚師托普", subname = nil}
MultiLanguageNpcData['tw'][66066] = {name = "日行者戴斯可", subname = "曦逐者酋長"}
MultiLanguageNpcData['tw'][66072] = {name = "崑萊難民01", subname = nil}
MultiLanguageNpcData['tw'][66074] = {name = "崑萊難民02", subname = nil}
MultiLanguageNpcData['tw'][66126] = {name = "祖塔", subname = "有抱負的馴獸師"}
MultiLanguageNpcData['tw'][66135] = {name = "『好勇鬥狠』達格拉", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66136] = {name = "安納琳", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66212] = {name = "食人妖高階祭司", subname = nil}
MultiLanguageNpcData['tw'][66278] = {name = "狂野小鬼", subname = nil}
MultiLanguageNpcData['tw'][66292] = {name = "空軍上將羅傑斯", subname = nil}
MultiLanguageNpcData['tw'][66300] = {name = "天火號船員", subname = nil}
MultiLanguageNpcData['tw'][66352] = {name = "背叛者格魯克", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66365] = {name = "翠玉觸鬚", subname = nil}
MultiLanguageNpcData['tw'][66370] = {name = "上將羅傑斯的私人旋翼機", subname = nil}
MultiLanguageNpcData['tw'][66398] = {name = "卡爾洛夏蠻兵", subname = nil}
MultiLanguageNpcData['tw'][66412] = {name = "艾蓮娜·振翼", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66422] = {name = "凱珊卓·卡蹦", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66436] = {name = "『強者』葛瑞森", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66442] = {name = "周坦", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66448] = {name = "迷霧蜥蜴", subname = nil}
MultiLanguageNpcData['tw'][66452] = {name = "凱拉·恐怖圖騰", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66460] = {name = "天火旋翼機駕駛", subname = nil}
MultiLanguageNpcData['tw'][66466] = {name = "石冷·崔西", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66473] = {name = "天火旋翼機", subname = nil}
MultiLanguageNpcData['tw'][66478] = {name = "大衛·科斯", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66512] = {name = "戴莎·瘟角", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66515] = {name = "闊塔斯·暗錘", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66518] = {name = "艾弗瑞沙", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66520] = {name = "杜林·暗錘", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66522] = {name = "黎蒂雅·艾柯斯塔", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66550] = {name = "尼奇·小型技術", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66551] = {name = "雷森", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66552] = {name = "納羅克", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66553] = {name = "長者莫魯魯", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66557] = {name = "血騎士安塔利", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66561] = {name = "果瑪·阿薩", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66579] = {name = "小寡婦蜘蛛", subname = nil}
MultiLanguageNpcData['tw'][66580] = {name = "蜘蛛", subname = nil}
MultiLanguageNpcData['tw'][66583] = {name = "塔蘭·祝", subname = "影潘宗主"}
MultiLanguageNpcData['tw'][66601] = {name = "烈焰之子", subname = nil}
MultiLanguageNpcData['tw'][66603] = {name = "瑞爾·夜風", subname = "軍情七處"}
MultiLanguageNpcData['tw'][66635] = {name = "畢格·疾熔", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66636] = {name = "『差點頭不保』的雅格布", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66638] = {name = "奧庫特·龍荒", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66639] = {name = "腸嘔", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66641] = {name = "天火號船員", subname = nil}
MultiLanguageNpcData['tw'][66656] = {name = "納茲格寧姆將軍", subname = nil}
MultiLanguageNpcData['tw'][66663] = {name = "螳螂人飛行者", subname = nil}
MultiLanguageNpcData['tw'][66664] = {name = "征服飛龍", subname = nil}
MultiLanguageNpcData['tw'][66669] = {name = "龍墳奴役者", subname = nil}
MultiLanguageNpcData['tw'][66674] = {name = "砲艇砲台", subname = nil}
MultiLanguageNpcData['tw'][66675] = {name = "佩恩少校", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66697] = {name = "瑞爾·夜風", subname = "軍情七處"}
MultiLanguageNpcData['tw'][66727] = {name = "柯克席克滲透者", subname = nil}
MultiLanguageNpcData['tw'][66730] = {name = "寺裡的懷雅", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66733] = {name = "摩洛卡", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66734] = {name = "農夫妮希", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66738] = {name = "勇敢的雍", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66739] = {name = "『荒行者』塾", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66741] = {name = "『天選』雅姬", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66747] = {name = "血池怪", subname = nil}
MultiLanguageNpcData['tw'][66796] = {name = "多倫隊長", subname = nil}
MultiLanguageNpcData['tw'][66815] = {name = "博丁·穩拳", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66819] = {name = "布拉克", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66822] = {name = "苟斯·禍怒", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][66824] = {name = "歐巴里斯", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66855] = {name = "瑞爾·夜風", subname = "軍情七處"}
MultiLanguageNpcData['tw'][66856] = {name = "空軍上將羅傑斯", subname = nil}
MultiLanguageNpcData['tw'][66865] = {name = "比克斯·挑彈手", subname = nil}
MultiLanguageNpcData['tw'][66866] = {name = "疤牙", subname = nil}
MultiLanguageNpcData['tw'][66871] = {name = "『智者』威利", subname = nil}
MultiLanguageNpcData['tw'][66872] = {name = "憤怒的小范", subname = nil}
MultiLanguageNpcData['tw'][66896] = {name = "強臂旋翼機", subname = nil}
MultiLanguageNpcData['tw'][66897] = {name = "強臂旋翼機", subname = nil}
MultiLanguageNpcData['tw'][66913] = {name = "Stormwind to Pandatia - Alliance intro Scene - CLIENT-SIDE - JSB", subname = nil}
MultiLanguageNpcData['tw'][66915] = {name = "柯爾克隆精英", subname = nil}
MultiLanguageNpcData['tw'][66918] = {name = "追尋者薩世席", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][66919] = {name = "『醃漬王』蘇利·麥拉利", subname = "軍情七處"}
MultiLanguageNpcData['tw'][66921] = {name = "密西卡", subname = "軍情七處"}
MultiLanguageNpcData['tw'][66922] = {name = "琥珀·吉爾妮", subname = "軍情七處"}
MultiLanguageNpcData['tw'][66924] = {name = "妮姆·代碼傑克", subname = "軍情七處"}
MultiLanguageNpcData['tw'][66927] = {name = "諾德·代碼傑克", subname = "軍情七處"}
MultiLanguageNpcData['tw'][66931] = {name = "暴風城士兵", subname = nil}
MultiLanguageNpcData['tw'][66942] = {name = "鬼煞", subname = nil}
MultiLanguageNpcData['tw'][66961] = {name = "納茲格寧姆將軍", subname = nil}
MultiLanguageNpcData['tw'][66993] = {name = "海倫娜·斯坦頓", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][67003] = {name = "塔蘭·祝", subname = "影潘宗主"}
MultiLanguageNpcData['tw'][67011] = {name = "卡爾洛夏蠻兵", subname = nil}
MultiLanguageNpcData['tw'][67063] = {name = "天火號轟炸機", subname = nil}
MultiLanguageNpcData['tw'][67067] = {name = "瑞爾的旋翼機", subname = nil}
MultiLanguageNpcData['tw'][67068] = {name = "瑞爾的旋翼機", subname = nil}
MultiLanguageNpcData['tw'][67158] = {name = "柯爾克隆精英", subname = nil}
MultiLanguageNpcData['tw'][67159] = {name = "白虎寺武僧", subname = nil}
MultiLanguageNpcData['tw'][67249] = {name = "熊貓人奴隸", subname = "熊貓人奴隸"}
MultiLanguageNpcData['tw'][67281] = {name = "潤滑工人", subname = nil}
MultiLanguageNpcData['tw'][67304] = {name = "鐵壁步卒", subname = nil}
MultiLanguageNpcData['tw'][67334] = {name = "血柄榮譽守衛", subname = "血柄榮譽守衛"}
MultiLanguageNpcData['tw'][67344] = {name = "迅捷灰狼", subname = nil}
MultiLanguageNpcData['tw'][67359] = {name = "天火旋翼機X2", subname = nil}
MultiLanguageNpcData['tw'][67370] = {name = "傑瑞米·菲索", subname = "大師級馴獸師"}
MultiLanguageNpcData['tw'][67386] = {name = "空軍上將羅傑斯", subname = nil}
MultiLanguageNpcData['tw'][67387] = {name = "技工大師歐沃斯巴克", subname = "地精工程學首席建築師"}
MultiLanguageNpcData['tw'][67395] = {name = "灘頭石毀車", subname = nil}
MultiLanguageNpcData['tw'][67461] = {name = "督軍血柄", subname = nil}
MultiLanguageNpcData['tw'][67493] = {name = "攻城旋翼4000", subname = nil}
MultiLanguageNpcData['tw'][67496] = {name = "擾困坦克9000型", subname = nil}
MultiLanguageNpcData['tw'][67560] = {name = "瓦里安·烏瑞恩國王", subname = "暴風之王"}
MultiLanguageNpcData['tw'][67607] = {name = "超級克普羅德2500", subname = "限量版"}
MultiLanguageNpcData['tw'][67634] = {name = "充分供應增益兔子", subname = nil}
MultiLanguageNpcData['tw'][67666] = {name = "充分進食增益兔子", subname = nil}
MultiLanguageNpcData['tw'][67679] = {name = "恆光水黽", subname = nil}
MultiLanguageNpcData['tw'][67687] = {name = "特殊攻擊管理員", subname = nil}
MultiLanguageNpcData['tw'][67733] = {name = "被激勵的增益兔子", subname = nil}
MultiLanguageNpcData['tw'][67761] = {name = "赤吉", subname = "紅鶴"}
MultiLanguageNpcData['tw'][67765] = {name = "天火旋翼機駕駛", subname = nil}
MultiLanguageNpcData['tw'][67768] = {name = "沼澤蚱蜢", subname = nil}
MultiLanguageNpcData['tw'][67771] = {name = "珀光螢火蟲", subname = nil}
MultiLanguageNpcData['tw'][67801] = {name = "大元帥塔文布萊德", subname = nil}
MultiLanguageNpcData['tw'][67808] = {name = "錦魚人勞工兔子", subname = nil}
MultiLanguageNpcData['tw'][67817] = {name = "泡泡陷阱載具", subname = nil}
MultiLanguageNpcData['tw'][67822] = {name = "雄獅灘精英", subname = nil}
MultiLanguageNpcData['tw'][67867] = {name = "卡爾洛斯·地獄吼", subname = "大酋長"}
MultiLanguageNpcData['tw'][67897] = {name = "地精飛行器", subname = nil}
MultiLanguageNpcData['tw'][67936] = {name = "地精勞工兔子", subname = nil}
MultiLanguageNpcData['tw'][67938] = {name = "充分潤滑增益兔子", subname = nil}
MultiLanguageNpcData['tw'][67941] = {name = "滑膩的蛇", subname = nil}
MultiLanguageNpcData['tw'][67959] = {name = "技工大師歐沃斯巴克", subname = "地精工程學首席建築師"}
MultiLanguageNpcData['tw'][67961] = {name = "地精器具兔子", subname = nil}
MultiLanguageNpcData['tw'][67967] = {name = "鐵壁機械搗碎機", subname = nil}
MultiLanguageNpcData['tw'][67973] = {name = "吉恩·葛雷邁恩", subname = nil}
MultiLanguageNpcData['tw'][67975] = {name = "被激勵的增益兔子", subname = nil}
MultiLanguageNpcData['tw'][67976] = {name = "技工大師歐沃斯巴克", subname = "地精工程學首席建築師"}
MultiLanguageNpcData['tw'][68003] = {name = "美猴王", subname = nil}
MultiLanguageNpcData['tw'][68004] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][68005] = {name = "翠玉督軍", subname = nil}
MultiLanguageNpcData['tw'][68018] = {name = "裘貝卡·破影者", subname = "惡魔學識大師"}
MultiLanguageNpcData['tw'][68019] = {name = "坎瑞薩德·埃伯洛克", subname = "黑穫議會領袖"}
MultiLanguageNpcData['tw'][68025] = {name = "索爾", subname = nil}
MultiLanguageNpcData['tw'][68038] = {name = "阿格拉", subname = nil}
MultiLanguageNpcData['tw'][68052] = {name = "奪日者居民", subname = nil}
MultiLanguageNpcData['tw'][68059] = {name = "索爾", subname = nil}
MultiLanguageNpcData['tw'][68084] = {name = "洛索瑪·塞隆", subname = "奎爾薩拉斯攝政王"}
MultiLanguageNpcData['tw'][68098] = {name = "灰舌勞工", subname = nil}
MultiLanguageNpcData['tw'][68101] = {name = "矮人勞工兔子", subname = nil}
MultiLanguageNpcData['tw'][68103] = {name = "被激勵的增益兔子", subname = nil}
MultiLanguageNpcData['tw'][68106] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][68108] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68116] = {name = "Loaded for Bear Buff Bunny", subname = nil}
MultiLanguageNpcData['tw'][68138] = {name = "火箭雞", subname = nil}
MultiLanguageNpcData['tw'][68145] = {name = "軍團薩提爾", subname = nil}
MultiLanguageNpcData['tw'][68147] = {name = "伊利達瑞·薩提爾", subname = nil}
MultiLanguageNpcData['tw'][68150] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][68151] = {name = "秩序精華", subname = nil}
MultiLanguageNpcData['tw'][68210] = {name = "矮人建築工地", subname = nil}
MultiLanguageNpcData['tw'][68213] = {name = "工作完成", subname = nil}
MultiLanguageNpcData['tw'][68214] = {name = "錦魚人建築工地", subname = nil}
MultiLanguageNpcData['tw'][68235] = {name = "吉恩·葛雷邁恩", subname = nil}
MultiLanguageNpcData['tw'][68263] = {name = "熊貓人煙火", subname = nil}
MultiLanguageNpcData['tw'][68278] = {name = "洛索瑪·塞隆", subname = "奎爾薩拉斯攝政王"}
MultiLanguageNpcData['tw'][68287] = {name = "貝恩·血蹄", subname = "牛頭人酋長"}
MultiLanguageNpcData['tw'][68289] = {name = "希瑞", subname = nil}
MultiLanguageNpcData['tw'][68303] = {name = "熊貓人勞工兔子", subname = nil}
MultiLanguageNpcData['tw'][68324] = {name = "狗毛增益兔子", subname = nil}
MultiLanguageNpcData['tw'][68327] = {name = "暴躁螢火蟲", subname = nil}
MultiLanguageNpcData['tw'][68330] = {name = "熔爐兔子", subname = nil}
MultiLanguageNpcData['tw'][68357] = {name = "衫·基恩", subname = "考倫督軍"}
MultiLanguageNpcData['tw'][68358] = {name = "織懼者阿法圖", subname = nil}
MultiLanguageNpcData['tw'][68359] = {name = "熊貓人沉睡兔子", subname = nil}
MultiLanguageNpcData['tw'][68396] = {name = "岩石", subname = nil}
MultiLanguageNpcData['tw'][68412] = {name = "Iron Fisted Buff Bunny", subname = nil}
MultiLanguageNpcData['tw'][68415] = {name = "Crypt Bunny", subname = nil}
MultiLanguageNpcData['tw'][68462] = {name = "流動的熊貓人古靈", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][68463] = {name = "燃燒的熊貓人古靈", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][68464] = {name = "低語的熊貓人古靈", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][68465] = {name = "雷霆的熊貓人古靈", subname = "宗師級馴獸師"}
MultiLanguageNpcData['tw'][68474] = {name = "指揮官疤口", subname = nil}
MultiLanguageNpcData['tw'][68477] = {name = "柯爾克隆哨衛", subname = nil}
MultiLanguageNpcData['tw'][68482] = {name = "銀月學者", subname = nil}
MultiLanguageNpcData['tw'][68500] = {name = "重金屬增益兔子", subname = nil}
MultiLanguageNpcData['tw'][68509] = {name = "火箭雞", subname = nil}
MultiLanguageNpcData['tw'][68511] = {name = "旁白先生", subname = nil}
MultiLanguageNpcData['tw'][68513] = {name = "泥沼水貍", subname = nil}
MultiLanguageNpcData['tw'][68518] = {name = "GNOME Trap Bunny", subname = nil}
MultiLanguageNpcData['tw'][68609] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68612] = {name = "天刃哨兵", subname = nil}
MultiLanguageNpcData['tw'][68613] = {name = "被驅離的奪日者", subname = nil}
MultiLanguageNpcData['tw'][68651] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68652] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68677] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68683] = {name = "NIGHT ELF Manual Labor Bunny", subname = nil}
MultiLanguageNpcData['tw'][68689] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68690] = {name = "瓦里安·烏瑞恩國王", subname = "暴風之王"}
MultiLanguageNpcData['tw'][68702] = {name = "Night Elf Buff Bunny", subname = nil}
MultiLanguageNpcData['tw'][68749] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68766] = {name = "不屈的奪日者", subname = nil}
MultiLanguageNpcData['tw'][68771] = {name = "大裝甲獅鷲獸", subname = nil}
MultiLanguageNpcData['tw'][68773] = {name = "大裝甲雙足翼龍", subname = nil}
MultiLanguageNpcData['tw'][68776] = {name = "被激勵的增益兔子", subname = nil}
MultiLanguageNpcData['tw'][68777] = {name = "美猴王", subname = nil}
MultiLanguageNpcData['tw'][68795] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][68812] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][68817] = {name = "Finale Controller Bunny", subname = nil}
MultiLanguageNpcData['tw'][68837] = {name = "地精飛行器", subname = nil}
MultiLanguageNpcData['tw'][68842] = {name = "泰蘭妲·語風", subname = "伊露恩的高階女祭司"}
MultiLanguageNpcData['tw'][68880] = {name = "柯爾克隆殺戮者", subname = nil}
MultiLanguageNpcData['tw'][68881] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][68882] = {name = "卡爾洛斯·地獄吼", subname = "大酋長"}
MultiLanguageNpcData['tw'][68894] = {name = "熊貓人建築工地", subname = nil}
MultiLanguageNpcData['tw'][68895] = {name = "熊貓人建築工地", subname = nil}
MultiLanguageNpcData['tw'][68896] = {name = "夜精靈建築工地", subname = nil}
MultiLanguageNpcData['tw'][68897] = {name = "夜精靈建築工地", subname = nil}
MultiLanguageNpcData['tw'][68898] = {name = "錦魚人建築工地", subname = nil}
MultiLanguageNpcData['tw'][68899] = {name = "地精建築工地", subname = nil}
MultiLanguageNpcData['tw'][68900] = {name = "地精建築工地", subname = nil}
MultiLanguageNpcData['tw'][68901] = {name = "矮人建築工地", subname = nil}
MultiLanguageNpcData['tw'][68904] = {name = "蘇茵", subname = "慍妃"}
MultiLanguageNpcData['tw'][68905] = {name = "盧凜", subname = "孤妃"}
MultiLanguageNpcData['tw'][68918] = {name = "Divine Bell Bunny", subname = nil}
MultiLanguageNpcData['tw'][68921] = {name = "瓦里安·烏瑞恩國王", subname = "暴風之王"}
MultiLanguageNpcData['tw'][68922] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68925] = {name = "年輕的瓦里安·烏瑞恩", subname = nil}
MultiLanguageNpcData['tw'][68927] = {name = "『專喬事情』老童", subname = "旅店老闆"}
MultiLanguageNpcData['tw'][68937] = {name = "Finale Controller Bunny", subname = nil}
MultiLanguageNpcData['tw'][68966] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68970] = {name = "沃金", subname = nil}
MultiLanguageNpcData['tw'][68972] = {name = "珍娜·普勞德摩爾女士", subname = "祈倫托領袖"}
MultiLanguageNpcData['tw'][68978] = {name = "奪日者難民", subname = "奪日者難民"}
MultiLanguageNpcData['tw'][69018] = {name = "完全一般兔子(JSB)", subname = nil}
MultiLanguageNpcData['tw'][69025] = {name = "指揮官疤口", subname = nil}
MultiLanguageNpcData['tw'][69026] = {name = "瓦里安·烏瑞恩國王", subname = "暴風之王"}
MultiLanguageNpcData['tw'][69028] = {name = "Generic Client-Side Bunny", subname = nil}
MultiLanguageNpcData['tw'][69045] = {name = "卡爾洛斯", subname = "地獄吼之子"}
MultiLanguageNpcData['tw'][69048] = {name = "希瓦娜斯·風行者(高等精靈)", subname = nil}
MultiLanguageNpcData['tw'][69161] = {name = "烏達斯塔", subname = nil}
MultiLanguageNpcData['tw'][69170] = {name = "贊達拉平民", subname = nil}
MultiLanguageNpcData['tw'][69257] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][69294] = {name = "贊達拉血衛士", subname = nil}
MultiLanguageNpcData['tw'][69295] = {name = "贊達拉侍祭", subname = nil}
MultiLanguageNpcData['tw'][69296] = {name = "贊達拉轉魂師", subname = nil}
MultiLanguageNpcData['tw'][69601] = {name = "強力炸藥", subname = nil}
MultiLanguageNpcData['tw'][69651] = {name = "戰神阿裘卡拉", subname = nil}
MultiLanguageNpcData['tw'][69652] = {name = "衫布", subname = nil}
MultiLanguageNpcData['tw'][69654] = {name = "雷神", subname = "雷霆之王"}
MultiLanguageNpcData['tw'][69755] = {name = "戰神阿裘卡拉", subname = nil}
MultiLanguageNpcData['tw'][69782] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][69888] = {name = "萊公", subname = "墮落的風暴守護者"}
MultiLanguageNpcData['tw'][69890] = {name = "藍毛小熊貓", subname = nil}
MultiLanguageNpcData['tw'][69915] = {name = "拉斯塔哈王", subname = nil}
MultiLanguageNpcData['tw'][69918] = {name = "祖爾", subname = nil}
MultiLanguageNpcData['tw'][69945] = {name = "贊達拉榮譽守衛", subname = nil}
MultiLanguageNpcData['tw'][69950] = {name = "納迦幻影怪", subname = "納迦幻影怪"}
MultiLanguageNpcData['tw'][70052] = {name = "惡魔靈魂井", subname = nil}
MultiLanguageNpcData['tw'][70084] = {name = "泰瑞納斯·米奈希爾", subname = nil}
MultiLanguageNpcData['tw'][70116] = {name = "魔古平民", subname = nil}
MultiLanguageNpcData['tw'][70225] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][70261] = {name = "Placeholder Creature", subname = nil}
MultiLanguageNpcData['tw'][70279] = {name = "茉艾拉·索瑞森", subname = "黑鐵攝政女王"}
MultiLanguageNpcData['tw'][70335] = {name = "紀·火爪", subname = "火金大師"}
MultiLanguageNpcData['tw'][70438] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][70473] = {name = "霜鬃獵頭者", subname = nil}
MultiLanguageNpcData['tw'][70476] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][70543] = {name = "贊達拉仇恨煽動者", subname = nil}
MultiLanguageNpcData['tw'][70626] = {name = "冥淵火", subname = nil}
MultiLanguageNpcData['tw'][70789] = {name = "贊達拉之怒旌旗", subname = nil}
MultiLanguageNpcData['tw'][70799] = {name = "瓦里安·烏瑞恩國王", subname = "暴風之王"}
MultiLanguageNpcData['tw'][70921] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][70968] = {name = "柯爾克隆好戰者", subname = nil}
MultiLanguageNpcData['tw'][70971] = {name = "森金守護者", subname = nil}
MultiLanguageNpcData['tw'][70972] = {name = "森金看守者", subname = nil}
MultiLanguageNpcData['tw'][70974] = {name = "廟門", subname = nil}
MultiLanguageNpcData['tw'][70978] = {name = "沃金", subname = nil}
MultiLanguageNpcData['tw'][70980] = {name = "先知昊范州", subname = nil}
MultiLanguageNpcData['tw'][70986] = {name = "柯爾克隆中尉", subname = nil}
MultiLanguageNpcData['tw'][70989] = {name = "玉龍", subname = "玉蛟"}
MultiLanguageNpcData['tw'][71003] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71008] = {name = "柯爾克隆傘兵", subname = nil}
MultiLanguageNpcData['tw'][71029] = {name = "玉龍挑戰銅鑼", subname = nil}
MultiLanguageNpcData['tw'][71039] = {name = "貧瘠之地車隊運輸車", subname = nil}
MultiLanguageNpcData['tw'][71040] = {name = "貧瘠之地車隊科多獸", subname = nil}
MultiLanguageNpcData['tw'][71044] = {name = "基瑞克", subname = nil}
MultiLanguageNpcData['tw'][71063] = {name = "先知昊范州", subname = nil}
MultiLanguageNpcData['tw'][71065] = {name = "塔蘭·祝", subname = "影潘宗主"}
MultiLanguageNpcData['tw'][71066] = {name = "柯爾克隆監督者", subname = nil}
MultiLanguageNpcData['tw'][71083] = {name = "塔蘭·祝", subname = "影潘宗主"}
MultiLanguageNpcData['tw'][71089] = {name = "日行者戴斯可", subname = "曦逐者酋長"}
MultiLanguageNpcData['tw'][71105] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71108] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71109] = {name = "雪怒挑戰銅鑼", subname = nil}
MultiLanguageNpcData['tw'][71113] = {name = "柯爾克隆神槍手", subname = nil}
MultiLanguageNpcData['tw'][71114] = {name = "柯爾克隆卓識者", subname = nil}
MultiLanguageNpcData['tw'][71116] = {name = "柯爾克隆戰狼", subname = nil}
MultiLanguageNpcData['tw'][71126] = {name = "迅捷藍色迅猛龍", subname = nil}
MultiLanguageNpcData['tw'][71127] = {name = "迅捷橄欖綠迅猛龍", subname = nil}
MultiLanguageNpcData['tw'][71128] = {name = "迅捷橘色迅猛龍", subname = nil}
MultiLanguageNpcData['tw'][71132] = {name = "『美聲』祖魯", subname = nil}
MultiLanguageNpcData['tw'][71139] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71142] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71144] = {name = "怒兆", subname = "玄牛"}
MultiLanguageNpcData['tw'][71146] = {name = "怒兆挑戰銅鑼", subname = nil}
MultiLanguageNpcData['tw'][71147] = {name = "沃金", subname = nil}
MultiLanguageNpcData['tw'][71148] = {name = "沃金", subname = nil}
MultiLanguageNpcData['tw'][71149] = {name = "索爾", subname = nil}
MultiLanguageNpcData['tw'][71150] = {name = "老陳·風暴烈酒", subname = nil}
MultiLanguageNpcData['tw'][71151] = {name = "貝恩·血蹄", subname = "牛頭人酋長"}
MultiLanguageNpcData['tw'][71165] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71166] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71169] = {name = "赤吉", subname = "紅鶴"}
MultiLanguageNpcData['tw'][71170] = {name = "赤吉挑戰銅鑼", subname = nil}
MultiLanguageNpcData['tw'][71172] = {name = "暗矛蝠騎兵", subname = nil}
MultiLanguageNpcData['tw'][71173] = {name = "暗矛蝙蝠", subname = nil}
MultiLanguageNpcData['tw'][71224] = {name = "波貝的神鼓", subname = nil}
MultiLanguageNpcData['tw'][71249] = {name = "貝恩·血蹄", subname = "牛頭人酋長"}
MultiLanguageNpcData['tw'][71250] = {name = "沃金", subname = nil}
MultiLanguageNpcData['tw'][71263] = {name = "暗矛俘虜", subname = nil}
MultiLanguageNpcData['tw'][71269] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['tw'][71275] = {name = "暗矛俘虜", subname = nil}
MultiLanguageNpcData['tw'][71281] = {name = "森金守護者", subname = nil}
MultiLanguageNpcData['tw'][71282] = {name = "森金看守者", subname = nil}
MultiLanguageNpcData['tw'][71283] = {name = "森金看守者", subname = nil}
MultiLanguageNpcData['tw'][71285] = {name = "森金守護者", subname = nil}
MultiLanguageNpcData['tw'][71288] = {name = "柯爾克隆占兆師", subname = nil}
MultiLanguageNpcData['tw'][71290] = {name = "暗矛蝠騎兵", subname = nil}
MultiLanguageNpcData['tw'][71291] = {name = "暗矛蝙蝠", subname = nil}
MultiLanguageNpcData['tw'][71305] = {name = "森金守護者", subname = nil}
MultiLanguageNpcData['tw'][71306] = {name = "森金守護者", subname = nil}
MultiLanguageNpcData['tw'][71307] = {name = "森金守衛", subname = nil}
MultiLanguageNpcData['tw'][71308] = {name = "森金守衛", subname = nil}
MultiLanguageNpcData['tw'][71317] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71319] = {name = "森金看守者", subname = nil}
MultiLanguageNpcData['tw'][71344] = {name = "索爾", subname = nil}
MultiLanguageNpcData['tw'][71345] = {name = "老陳·風暴烈酒", subname = nil}
MultiLanguageNpcData['tw'][71352] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71373] = {name = "暗矛俘虜", subname = nil}
MultiLanguageNpcData['tw'][71374] = {name = "暗矛俘虜", subname = nil}
MultiLanguageNpcData['tw'][71375] = {name = "暗矛俘虜", subname = nil}
MultiLanguageNpcData['tw'][71377] = {name = "暗矛俘虜", subname = nil}
MultiLanguageNpcData['tw'][71387] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71404] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71424] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71426] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71429] = {name = "淨化小浪", subname = nil}
MultiLanguageNpcData['tw'][71434] = {name = "雪怒的影像", subname = nil}
MultiLanguageNpcData['tw'][71435] = {name = "玉龍的影像", subname = nil}
MultiLanguageNpcData['tw'][71439] = {name = "怒兆的影像", subname = nil}
MultiLanguageNpcData['tw'][71441] = {name = "赤吉的影像", subname = nil}
MultiLanguageNpcData['tw'][71457] = {name = "榮譽看臺旋翼機", subname = nil}
MultiLanguageNpcData['tw'][71504] = {name = "攻城機匠黑引信", subname = "黑引信有限公司"}
MultiLanguageNpcData['tw'][71514] = {name = "鑼", subname = nil}
MultiLanguageNpcData['tw'][71589] = {name = "繁花掘地工", subname = nil}
MultiLanguageNpcData['tw'][71718] = {name = "繁花掘地工", subname = nil}
MultiLanguageNpcData['tw'][71794] = {name = "『智多星』狡星", subname = nil}
MultiLanguageNpcData['tw'][71865] = {name = "卡爾洛斯·地獄吼", subname = "大酋長"}
MultiLanguageNpcData['tw'][71887] = {name = "小麒麟獸", subname = nil}
MultiLanguageNpcData['tw'][71888] = {name = "鳳凰寶寶", subname = nil}
MultiLanguageNpcData['tw'][71890] = {name = "嗝爪", subname = nil}
MultiLanguageNpcData['tw'][71891] = {name = "巨型螳螂寶寶", subname = nil}
MultiLanguageNpcData['tw'][71892] = {name = "雲蛟", subname = nil}
MultiLanguageNpcData['tw'][71893] = {name = "琥珀幼蠍", subname = nil}
MultiLanguageNpcData['tw'][71894] = {name = "火爪", subname = nil}
MultiLanguageNpcData['tw'][71895] = {name = "雲蛟", subname = nil}
MultiLanguageNpcData['tw'][71896] = {name = "雲蛟", subname = nil}
MultiLanguageNpcData['tw'][71899] = {name = "小魁", subname = nil}
MultiLanguageNpcData['tw'][71900] = {name = "蒼脊", subname = nil}
MultiLanguageNpcData['tw'][71901] = {name = "毒鼬", subname = nil}
MultiLanguageNpcData['tw'][71902] = {name = "狼鼬", subname = nil}
MultiLanguageNpcData['tw'][71905] = {name = "查理", subname = nil}
MultiLanguageNpcData['tw'][71924] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][71931] = {name = "塔蘭·祝", subname = "影潘宗主"}
MultiLanguageNpcData['tw'][72316] = {name = "斥侯伊戈爾·柯爾蒂", subname = "雄獅之眼"}
MultiLanguageNpcData['tw'][72392] = {name = "沃金", subname = nil}
MultiLanguageNpcData['tw'][72394] = {name = "貝恩·血蹄", subname = "牛頭人酋長"}
MultiLanguageNpcData['tw'][72546] = {name = "柯爾克隆蠻兵", subname = nil}
MultiLanguageNpcData['tw'][72661] = {name = "熱誠之煞", subname = nil}
MultiLanguageNpcData['tw'][72694] = {name = "攻城機匠黑引信", subname = nil}
MultiLanguageNpcData['tw'][72695] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][72723] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][72724] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][72774] = {name = "『奸商』智多星", subname = nil}
MultiLanguageNpcData['tw'][72870] = {name = "凱洛斯", subname = nil}
MultiLanguageNpcData['tw'][72886] = {name = "延齡刃岩石切割機", subname = nil}
MultiLanguageNpcData['tw'][72887] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['tw'][72927] = {name = "科沃克", subname = nil}
MultiLanguageNpcData['tw'][72929] = {name = "斯拉席克琥珀大師", subname = nil}
MultiLanguageNpcData['tw'][72954] = {name = "柯爾克隆榮譽守衛", subname = nil}
MultiLanguageNpcData['tw'][72964] = {name = "哥洛丹", subname = "黑引信有限公司"}
MultiLanguageNpcData['tw'][72981] = {name = "阿格隆", subname = "黑引信有限公司"}
MultiLanguageNpcData['tw'][72986] = {name = "珊娜·火花", subname = "黑引信有限公司"}
MultiLanguageNpcData['tw'][73012] = {name = "聖螳雄兵", subname = nil}
MultiLanguageNpcData['tw'][73059] = {name = "柯爾克隆鋼鐵之星", subname = nil}
MultiLanguageNpcData['tw'][73061] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][73066] = {name = "博學行者阿洲", subname = nil}
MultiLanguageNpcData['tw'][73082] = {name = "李大師", subname = "天尊武道會主辦人"}
MultiLanguageNpcData['tw'][73084] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['tw'][73091] = {name = "黑引信傭兵", subname = "黑引信有限公司"}
MultiLanguageNpcData['tw'][73095] = {name = "黑引信工程師", subname = "黑引信有限公司"}
MultiLanguageNpcData['tw'][73098] = {name = "柯爾克隆監督者", subname = nil}
MultiLanguageNpcData['tw'][73126] = {name = "雪怒", subname = nil}
MultiLanguageNpcData['tw'][73127] = {name = "赤吉", subname = "紅鶴"}
MultiLanguageNpcData['tw'][73128] = {name = "玉龍", subname = "玉蛟"}
MultiLanguageNpcData['tw'][73130] = {name = "怒兆", subname = "玄牛"}
MultiLanguageNpcData['tw'][73133] = {name = "美猴王", subname = nil}
MultiLanguageNpcData['tw'][73134] = {name = "紹昊大帝", subname = nil}
MultiLanguageNpcData['tw'][73136] = {name = "博學行者阿洲", subname = nil}
MultiLanguageNpcData['tw'][73138] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][73149] = {name = "Quest - Legendary 5.4 - Tavern Flour Bunny - JSB", subname = nil}
MultiLanguageNpcData['tw'][73275] = {name = "Bottle Bunny", subname = nil}
MultiLanguageNpcData['tw'][73318] = {name = "博學行者阿洲", subname = nil}
MultiLanguageNpcData['tw'][73319] = {name = "怒西昂", subname = "黑龍王子"}
MultiLanguageNpcData['tw'][73346] = {name = "『專喬事情』老童", subname = "旅店老闆"}
MultiLanguageNpcData['tw'][73436] = {name = "VO Bunny", subname = nil}
MultiLanguageNpcData['tw'][73462] = {name = "卡爾洛斯·地獄吼", subname = "大酋長"}
MultiLanguageNpcData['tw'][73503] = {name = "赤吉的幼雛，赤祁", subname = nil}
MultiLanguageNpcData['tw'][73505] = {name = "雪怒的幼虎，雪福", subname = nil}
MultiLanguageNpcData['tw'][73506] = {name = "怒兆的幼犢，怒沼", subname = nil}
MultiLanguageNpcData['tw'][73507] = {name = "玉龍的血脈，玉朗", subname = nil}
MultiLanguageNpcData['tw'][73564] = {name = "格里斯·輪滑", subname = nil}
MultiLanguageNpcData['tw'][73569] = {name = "茉艾拉的鑽地機", subname = nil}
MultiLanguageNpcData['tw'][73573] = {name = "塵翼之蛾", subname = nil}
MultiLanguageNpcData['tw'][73592] = {name = "瓦里安·烏瑞恩國王", subname = "暴風之王"}
MultiLanguageNpcData['tw'][73593] = {name = "塔蘭·祝", subname = "影潘宗主"}
MultiLanguageNpcData['tw'][73598] = {name = "珍娜·普勞德摩爾女士", subname = nil}
MultiLanguageNpcData['tw'][73603] = {name = "貝恩·血蹄", subname = "牛頭人酋長"}
MultiLanguageNpcData['tw'][73604] = {name = "貿易親王加里維克斯", subname = "污水企業聯合負責人"}
MultiLanguageNpcData['tw'][73605] = {name = "洛索瑪·塞隆", subname = "奎爾薩拉斯攝政王"}
MultiLanguageNpcData['tw'][73606] = {name = "瓦娜斯·風行者女士", subname = "女妖之王"}
MultiLanguageNpcData['tw'][73607] = {name = "安杜因·烏瑞恩", subname = "暴風城王子"}
MultiLanguageNpcData['tw'][73626] = {name = "『戰寵新手』小湯米·紐康莫", subname = nil}
MultiLanguageNpcData['tw'][73716] = {name = "薩魯法爾霸王", subname = nil}
MultiLanguageNpcData['tw'][73811] = {name = "繁花掘地工", subname = nil}
MultiLanguageNpcData['tw'][73818] = {name = "延齡刃岩石切割機", subname = nil}
MultiLanguageNpcData['tw'][73828] = {name = "焰翼之蛾", subname = nil}
MultiLanguageNpcData['tw'][73829] = {name = "天翼之蛾", subname = nil}
MultiLanguageNpcData['tw'][73837] = {name = "皮耶爐", subname = "艾蜜莉·寇兒的夥伴"}
MultiLanguageNpcData['tw'][73927] = {name = "大工匠梅卡托克", subname = "地精之王"}
MultiLanguageNpcData['tw'][73942] = {name = "沃金", subname = nil}
MultiLanguageNpcData['tw'][73962] = {name = "泰蘭妲·語風", subname = "伊露恩的高階女祭司"}
MultiLanguageNpcData['tw'][73965] = {name = "惡魔戰馬", subname = nil}
MultiLanguageNpcData['tw'][73966] = {name = "恐懼戰馬", subname = nil}
MultiLanguageNpcData['tw'][74077] = {name = "火焰潘咪", subname = nil}
MultiLanguageNpcData['tw'][74130] = {name = "卡爾洛斯", subname = "地獄吼之子"}
MultiLanguageNpcData['tw'][74217] = {name = "大工匠梅卡托克", subname = "地精之王"}
MultiLanguageNpcData['tw'][166359] = {name = "祖利安猛虎", subname = nil}
MultiLanguageNpcData['tw'][173754] = {name = "瑪丁雷少校", subname = nil}
MultiLanguageNpcData['tw'][173758] = {name = "Overlord Runthak", subname = nil}
MultiLanguageNpcData['tw'][176437] = {name = "Heigan Aggro Trigger", subname = nil}
MultiLanguageNpcData['tw'][176443] = {name = "假人", subname = nil}
MultiLanguageNpcData['tw'][176525] = {name = "預言者斯克拉姆", subname = nil}
MultiLanguageNpcData['tw'][176546] = {name = "Call for Help Trigger", subname = nil}
MultiLanguageNpcData['tw'][176547] = {name = "Call for Help Trigger", subname = nil}
MultiLanguageNpcData['tw'][176552] = {name = "奧格瑪", subname = nil}
MultiLanguageNpcData['tw'][176708] = {name = "復甦的相位獵取者", subname = nil}
MultiLanguageNpcData['tw'][177659] = {name = "首領假人", subname = nil}
MultiLanguageNpcData['tw'][178420] = {name = "博學者阿斯塔樂·血誓", subname = nil}
MultiLanguageNpcData['tw'][178449] = {name = "普通獵人寵物", subname = nil}
MultiLanguageNpcData['tw'][181760] = {name = "競技場佈告欄", subname = nil}
MultiLanguageNpcData['tw'][185317] = {name = "夢魔", subname = nil}
MultiLanguageNpcData['tw'][185335] = {name = "受到召喚的夢魔", subname = nil}
MultiLanguageNpcData['tw'][185403] = {name = "賽里登‧遠尋者", subname = "考古學家"}
MultiLanguageNpcData['tw'][185404] = {name = "瑞拉索‧月歌", subname = "考古學家"}
MultiLanguageNpcData['tw'][189739] = {name = "卡魯耶克鯨骨滑翔翼", subname = nil}
MultiLanguageNpcData['tw'][194795] = {name = "魚語者爾塔斯克", subname = nil}
MultiLanguageNpcData['tw'][198525] = {name = "潰爛翡翠飛龍", subname = nil}
MultiLanguageNpcData['tw'][199387] = {name = "D3-BA", subname = "工程學供應商"}
MultiLanguageNpcData['tw'][199411] = {name = "地城裝備工", subname = "地城供應商"}
MultiLanguageNpcData['tw'][199649] = {name = "製作裝備工", subname = "製作裝備供應商"}
MultiLanguageNpcData['tw'][206038] = {name = "不朽粉碎觸手", subname = nil}
MultiLanguageNpcData['tw'][207128] = {name = "復生星宿", subname = "恆星精華貿易"}
MultiLanguageNpcData['tw'][211297] = {name = "白銀誓盟守望者", subname = nil}
MultiLanguageNpcData['tw'][211332] = {name = "庫拉林·霍普雷德", subname = "污染者的天譴石交換"}
MultiLanguageNpcData['tw'][211340] = {name = "克拉菈·碎夢者", subname = "污染者的天譴石交換"}
MultiLanguageNpcData['tw'][228792] = {name = "熔喉尖刺潛獵者", subname = nil}
MultiLanguageNpcData['tw'][234135] = {name = "藍晶石頭管理者", subname = "裂縫石碎片兌換"}
MultiLanguageNpcData['tw'][239945] = {name = "阿拉妮雅‧谷哮", subname = "熔岩前線招募員"}
MultiLanguageNpcData['tw'][240320] = {name = "酸液血珠", subname = "鬚瑪之血"}
MultiLanguageNpcData['tw'][240321] = {name = "黑暗血珠", subname = "鬚瑪之血"}
MultiLanguageNpcData['tw'][240322] = {name = "鈷藍血珠", subname = "鬚瑪之血"}
MultiLanguageNpcData['tw'][240323] = {name = "赤紅血珠", subname = "鬚瑪之血"}
MultiLanguageNpcData['tw'][240324] = {name = "發光血珠", subname = "鬚瑪之血"}
MultiLanguageNpcData['tw'][240325] = {name = "暗影血珠", subname = "鬚瑪之血"}
MultiLanguageNpcData['tw'][241008] = {name = "潰法力場", subname = nil}
MultiLanguageNpcData['tw'][241468] = {name = "札爾斯塔茲", subname = "黑曜石碎魂交易商"}
MultiLanguageNpcData['tw'][247440] = {name = "赤吉", subname = "紅鶴"}
MultiLanguageNpcData['tw'][247447] = {name = "赤吉", subname = "紅鶴"}
MultiLanguageNpcData['tw'][247730] = {name = "雪怒", subname = "白虎"}
MultiLanguageNpcData['tw'][247731] = {name = "怒兆", subname = "玄牛"}
MultiLanguageNpcData['tw'][247732] = {name = "玉龍", subname = "玉蛟"}
